version: '3'

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    networks:
      custom_network:
    env_file:
      - 'env.influxdb'
    volumes:
      - ./data/influxdb:/var/lib/influxdb

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    networks:
      custom_network:
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks:
      custom_network:
    ports:
      - "3000:3000"
    env_file:
      - 'env.grafana'
    volumes:
      - ./data/grafana:/var/lib/grafana

networks:
  custom_network:
    external: true