version: '3'

services:
  nginx-php-fpm:
    image: webdevops/php-nginx:7.3
    restart: always
    container_name: nginx-php
    ports:
      - 82:80
    networks:
      custom_network:
    environment:
      - WEB_DOCUMENT_ROOT=/app
      - WEB_DOCUMENT_INDEX=index.php
    volumes:
      - ./src:/app
      - ./src/conf/status.conf:/opt/docker/etc/nginx/vhost.common.d/status.conf

  db:
    image: mysql:5.7
    container_name: nginx-mysql
    ports:
      - 3306:3306
    networks:
      custom_network:
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=lesson_2
      - MYSQL_USER=lesson_2
      - MYSQL_PASSWORD=lesson_2
    volumes:
      - ./src/data:/var/lib/mysql
      - ./src/databases:/docker-entrypoint-initdb.d

networks:
  custom_network:
    external: true